### ISSUE TITLE
Your nav bar doesn't update the active element

### ISSUE THREAD

**Issue by ghost** [dhong44/dhong44.github.io#2]
Hi! While scrolling through your content, I noticed that your navigation bar on the right doesn't seem to update as I scroll through. I would expect behaviour like this
![image](https://user-images.githubusercontent.com/14363051/46239713-57b17f00-c36a-11e8-8d43-d5be039c1ca5.png)

Instead, this is what happens when I scroll down 
![image](https://user-images.githubusercontent.com/14363051/46239726-7ca5f200-c36a-11e8-96d4-85398136681b.png)

**Comment by dhong44** [comment]
It seems to be working for me. Could you describe any specific steps to reproduce this issue and what hardware you're running on?

**Comment by ghost** [comment]
Im on chrome using a surface. I did disable JS on the browser though. I find disabling JS keeps my browsing experience ad free which I like.

**Comment by dhong44** [comment]
If disabling JS is purely to avoid ads I would suggest downloading a chrome extension such as [1] or [2]. In a previous discussion [3] I explained why I believe JavaScript can be assumed to be enabled and is actually enabled by default on chrome.

[1] https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en
[2] https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom
[3] https://github.com/cshen98/cshen98.github.io/pull/1

**Comment by ghost** [comment]
ok
